### ISSUE TITLE
Subscriptions recovering from connection failures

### ISSUE THREAD

**Issue by tonyvanriet** [exponentially/extreme#72] opened 2021-01-13 22:56 UTC
Hi @burmajam !!

I'm in the process of improving how our subscriptions deal with EventStore connection failures. I wanted to check in with you to see if you've dealt with similar issues and make sure I'm not off track in any way.

The problem we've had is that when the connection to the EventStore is briefly lost, the extreme client recovers just fine, but our existing subscriptions no longer receive new events from their streams. The solution I'm pursuing is to modify our subscription process so that it also monitors the `Extreme.Connection` process. That way when the `Connection` process crashes, our subscription process can also crash and establish a new subscription after restart.

The disconnect I'm concerned with manifests in the application as a `:tcp_closed` message from `:gen_tcp`.

Our subscription process is our own wrapper around the extreme client that was originally patterned after the `MyApp.StreamSubscriber` example in the readme. This subscription process calls `read_and_stay_subscribed` and monitors the `Extreme.Subscription` pid that's returned. If I also monitor the `Extreme.Connection` process here and `:stop` when the `Connection` process goes `:DOWN`, I get the desired behavior. Our subscription process restarts and we re-subscribe.

Now that I look through the extreme client further, I'm a little concerned that this approach will result in orphaned `Extreme.Subscription` processes supervised by `Extreme.SubscriptionsSupervisor`. I'll have to dig into the extreme client further to really understand the implications. The question that just popped up is, would it be better for the extreme client to internally monitor the `Extreme.Connection` process from the `Extreme.Subscription` processes or from the `Extreme.SubscriptionsSupervisor` process. If you have any thoughts along those lines, I'd love to hear them.

Thank you much,
  ~Tony

**Comment by tonyvanriet** [comment] 2021-01-19 22:58
Hi again @burmajam,

I'm running with the change I described in our wrapper where we monitor the `Extreme.Connection` process and crash our subscription when the connection closes. Unfortunately though, I was able to prove though that this does result in orphaned `Extreme.ReadingSubscription` processes as children of the `Extreme.SubscriptionsSupervisor` and in the `subscriptions` lookup in the `Extreme.RequestManager`. It seems to me like extreme might want to do this process linking internally since the subscription processes and the `RequestManager` are dependent on the `Connection`. I tinkered with this briefly but ran into new problems and got concerned that I might be naive to some of the consequences of restarting these processes.

I'm fine with closing out this issue, or keeping it going with more discussion. Whatever you prefer.
Thanks!

**Comment by burmajam** [comment] 2021-01-20 11:23
Hi @tonyvanriet,

I can't say that we didn't see these problems, but it happened once in few months, and our monitoring systems used to alert us when listeners are not in sync with streams they listen. I'll try to reproduce the problem and then find the way for extreme to handle it correct way.

Thanks for reporting and stay tuned...

**Comment by tonyvanriet** [comment] 2021-01-20 15:38
Sounds good @burmajam , thanks.
We're in a similar situation where we've survived this way for a long time relying on monitoring of our listeners.

It's fairly easy to emulate by sending a `:tcp_closed` message into the `Connection`.
```
MyExtremeClient.Connection |> send({:tcp_closed, 1234})
```
After that, you should see that the subscription continues to run but longer sees any new events.

**Comment by cuddlecake** [comment] 2021-01-20 15:42
Heya,

if I may chime in, my work around has been to stop the SubscriptionsSupervisor whenever the connection to EventStore has been established:

https://github.com/cuddlecake/extreme/blob/b086e05e4a0d4051b1256f76bd98f2d854e36fc9/lib/extreme/connection.ex#L46

It's not good, but I also did not put much time in finding a better solution, since we don't use EventStore anymore.

**Comment by burmajam** [comment] 2021-01-26 11:35
Hi @tonyvanriet, I've just pushed fix https://github.com/exponentially/extreme/commit/15a102e21fc5063e97133b6c91943ea9a7c7768e. There's no unit test yet, but I've tried it with our integration tests and it works as expected now. Idea is that when connection receives `tcp_closed` it kills all subscriptions which on the other hand kill all subscribers/listeners. That's where your supervisor jumps in and restarts subscribers.

Please let me know if that works for you

**Closed as completed** 2021-03-01 10:24 UTC

**Comment by tonyvanriet** [comment] 2021-04-05 14:53
Oops, missed out on this notification a while back. Thanks for that fix. 
Will let you know when we make time to integrate it.
